export const projects = [
  {
    id: "1",
    name: "Website Redesign",
    description: "Redesign the company website",
    status: "In Progress",
    completionPercentage: 65,
    startDate: "2025-03-01",
    endDate: "2025-05-15",
    team: ["John Doe", "Jane Smith", "Alex Johnson"],
    client: "Acme Inc.",
  },
  {
    id: "2",
    name: "Mobile App Development",
    description: "Develop a new mobile application",
    status: "Planning",
    completionPercentage: 25,
    startDate: "2025-04-10",
    endDate: "2025-07-30",
    team: ["John Doe", "Mike Wilson", "Sarah Brown"],
    client: "TechCorp",
  },
  {
    id: "3",
    name: "Marketing Campaign",
    description: "Q2 Marketing Campaign",
    status: "Completed",
    completionPercentage: 100,
    startDate: "2025-01-15",
    endDate: "2025-03-31",
    team: ["Jane Smith", "Tom Davis"],
    client: "Acme Inc.",
  },
  {
    id: "4",
    name: "Product Launch",
    description: "New product launch preparation",
    status: "In Progress",
    completionPercentage: 45,
    startDate: "2025-03-15",
    endDate: "2025-06-01",
    team: ["John Doe", "Jane Smith", "Mike Wilson"],
    client: "GlobalTech",
  },
  {
    id: "5",
    name: "Infrastructure Upgrade",
    description: "Upgrade server infrastructure",
    status: "Planning",
    completionPercentage: 10,
    startDate: "2025-05-01",
    endDate: "2025-06-15",
    team: ["Alex Johnson", "Sarah Brown"],
    client: "InternalIT",
  },
]

// Project-specific todos
export const projectTodos = {
  "1": [
    {
      id: "1-1",
      title: "Design homepage mockup",
      description: "Create mockups for the new homepage design",
      status: "completed",
      priority: "high",
      dueDate: "2025-04-10",
      assignedTo: "Jane Smith",
    },
    {
      id: "1-2",
      title: "Implement responsive layout",
      description: "Make sure the website works well on all devices",
      status: "in-progress",
      priority: "high",
      dueDate: "2025-04-20",
      assignedTo: "John Doe",
    },
    {
      id: "1-3",
      title: "Content migration",
      description: "Move content from old site to new site",
      status: "pending",
      priority: "medium",
      dueDate: "2025-04-25",
      assignedTo: "Alex Johnson",
    },
    {
      id: "1-4",
      title: "SEO optimization",
      description: "Optimize the website for search engines",
      status: "pending",
      priority: "medium",
      dueDate: "2025-04-28",
      assignedTo: "Jane Smith",
    },
    {
      id: "1-5",
      title: "User testing",
      description: "Conduct user testing sessions",
      status: "pending",
      priority: "high",
      dueDate: "2025-05-05",
      assignedTo: "John Doe",
    },
  ],
  "2": [
    {
      id: "2-1",
      title: "Define app requirements",
      description: "Document all app requirements and features",
      status: "completed",
      priority: "high",
      dueDate: "2025-04-15",
      assignedTo: "John Doe",
    },
    {
      id: "2-2",
      title: "Create wireframes",
      description: "Design wireframes for all app screens",
      status: "in-progress",
      priority: "high",
      dueDate: "2025-04-25",
      assignedTo: "Sarah Brown",
    },
    {
      id: "2-3",
      title: "Setup development environment",
      description: "Prepare development environment and tools",
      status: "completed",
      priority: "medium",
      dueDate: "2025-04-18",
      assignedTo: "Mike Wilson",
    },
    {
      id: "2-4",
      title: "API design",
      description: "Design API endpoints for the app",
      status: "pending",
      priority: "medium",
      dueDate: "2025-04-30",
      assignedTo: "Mike Wilson",
    },
    {
      id: "2-5",
      title: "UI design",
      description: "Create UI design for the app",
      status: "pending",
      priority: "high",
      dueDate: "2025-05-10",
      assignedTo: "Sarah Brown",
    },
  ],
  "3": [
    {
      id: "3-1",
      title: "Define campaign goals",
      description: "Set clear goals for the marketing campaign",
      status: "completed",
      priority: "high",
      dueDate: "2025-01-20",
      assignedTo: "Jane Smith",
    },
    {
      id: "3-2",
      title: "Create content calendar",
      description: "Plan content for the entire campaign period",
      status: "completed",
      priority: "medium",
      dueDate: "2025-01-25",
      assignedTo: "Tom Davis",
    },
    {
      id: "3-3",
      title: "Design social media assets",
      description: "Create graphics for social media posts",
      status: "completed",
      priority: "medium",
      dueDate: "2025-02-05",
      assignedTo: "Jane Smith",
    },
    {
      id: "3-4",
      title: "Launch email campaign",
      description: "Send out email newsletters",
      status: "completed",
      priority: "high",
      dueDate: "2025-02-15",
      assignedTo: "Tom Davis",
    },
    {
      id: "3-5",
      title: "Campaign performance analysis",
      description: "Analyze campaign results and prepare report",
      status: "completed",
      priority: "high",
      dueDate: "2025-03-25",
      assignedTo: "Jane Smith",
    },
  ],
  "4": [
    {
      id: "4-1",
      title: "Finalize product features",
      description: "Confirm all features for the product launch",
      status: "completed",
      priority: "high",
      dueDate: "2025-03-20",
      assignedTo: "John Doe",
    },
    {
      id: "4-2",
      title: "Create marketing materials",
      description: "Prepare all marketing materials for the launch",
      status: "in-progress",
      priority: "high",
      dueDate: "2025-04-15",
      assignedTo: "Jane Smith",
    },
    {
      id: "4-3",
      title: "Prepare press release",
      description: "Write and review press release",
      status: "completed",
      priority: "medium",
      dueDate: "2025-04-10",
      assignedTo: "Mike Wilson",
    },
    {
      id: "4-4",
      title: "Plan launch event",
      description: "Organize the product launch event",
      status: "in-progress",
      priority: "high",
      dueDate: "2025-05-01",
      assignedTo: "Jane Smith",
    },
    {
      id: "4-5",
      title: "Prepare sales team",
      description: "Train sales team on new product features",
      status: "pending",
      priority: "medium",
      dueDate: "2025-05-15",
      assignedTo: "John Doe",
    },
  ],
  "5": [
    {
      id: "5-1",
      title: "Assess current infrastructure",
      description: "Evaluate current server setup and needs",
      status: "completed",
      priority: "high",
      dueDate: "2025-05-05",
      assignedTo: "Alex Johnson",
    },
    {
      id: "5-2",
      title: "Research new solutions",
      description: "Research and compare server solutions",
      status: "in-progress",
      priority: "medium",
      dueDate: "2025-05-15",
      assignedTo: "Sarah Brown",
    },
    {
      id: "5-3",
      title: "Create migration plan",
      description: "Develop a plan for migrating to new infrastructure",
      status: "pending",
      priority: "high",
      dueDate: "2025-05-25",
      assignedTo: "Alex Johnson",
    },
    {
      id: "5-4",
      title: "Budget approval",
      description: "Get budget approval for the upgrade",
      status: "pending",
      priority: "high",
      dueDate: "2025-05-20",
      assignedTo: "Sarah Brown",
    },
    {
      id: "5-5",
      title: "Schedule downtime",
      description: "Plan and communicate server downtime",
      status: "pending",
      priority: "medium",
      dueDate: "2025-06-01",
      assignedTo: "Alex Johnson",
    },
  ],
}

// Project-specific links
export const projectLinks = {
  "1": [
    {
      id: "1-1",
      title: "Website Requirements Doc",
      url: "https://docs.example.com/website-requirements",
      category: "Documentation",
      createdAt: "2025-03-05",
      createdBy: "John Doe",
    },
    {
      id: "1-2",
      title: "Design System",
      url: "https://figma.com/design-system",
      category: "Design",
      createdAt: "2025-03-10",
      createdBy: "Jane Smith",
    },
    {
      id: "1-3",
      title: "Content Strategy",
      url: "https://docs.example.com/content-strategy",
      category: "Content",
      createdAt: "2025-03-15",
      createdBy: "Alex Johnson",
    },
    {
      id: "1-4",
      title: "Competitor Analysis",
      url: "https://docs.example.com/competitor-analysis",
      category: "Research",
      createdAt: "2025-03-20",
      createdBy: "John Doe",
    },
    {
      id: "1-5",
      title: "SEO Guidelines",
      url: "https://docs.example.com/seo-guidelines",
      category: "SEO",
      createdAt: "2025-03-25",
      createdBy: "Jane Smith",
    },
  ],
  "2": [
    {
      id: "2-1",
      title: "App Requirements Doc",
      url: "https://docs.example.com/app-requirements",
      category: "Documentation",
      createdAt: "2025-04-12",
      createdBy: "John Doe",
    },
    {
      id: "2-2",
      title: "UI/UX Guidelines",
      url: "https://figma.com/app-design",
      category: "Design",
      createdAt: "2025-04-14",
      createdBy: "Sarah Brown",
    },
    {
      id: "2-3",
      title: "API Documentation",
      url: "https://api.example.com/docs",
      category: "Development",
      createdAt: "2025-04-16",
      createdBy: "Mike Wilson",
    },
    {
      id: "2-4",
      title: "User Research",
      url: "https://docs.example.com/user-research",
      category: "Research",
      createdAt: "2025-04-18",
      createdBy: "Sarah Brown",
    },
    {
      id: "2-5",
      title: "Technology Stack",
      url: "https://docs.example.com/tech-stack",
      category: "Development",
      createdAt: "2025-04-20",
      createdBy: "Mike Wilson",
    },
  ],
  "3": [
    {
      id: "3-1",
      title: "Campaign Brief",
      url: "https://docs.example.com/campaign-brief",
      category: "Documentation",
      createdAt: "2025-01-16",
      createdBy: "Jane Smith",
    },
    {
      id: "3-2",
      title: "Content Calendar",
      url: "https://calendar.example.com/marketing",
      category: "Planning",
      createdAt: "2025-01-18",
      createdBy: "Tom Davis",
    },
    {
      id: "3-3",
      title: "Brand Guidelines",
      url: "https://brand.example.com",
      category: "Brand",
      createdAt: "2025-01-20",
      createdBy: "Jane Smith",
    },
    {
      id: "3-4",
      title: "Social Media Assets",
      url: "https://drive.example.com/social-assets",
      category: "Assets",
      createdAt: "2025-01-25",
      createdBy: "Tom Davis",
    },
    {
      id: "3-5",
      title: "Campaign Analytics",
      url: "https://analytics.example.com/campaign",
      category: "Analytics",
      createdAt: "2025-03-20",
      createdBy: "Jane Smith",
    },
  ],
  "4": [
    {
      id: "4-1",
      title: "Product Specifications",
      url: "https://docs.example.com/product-specs",
      category: "Documentation",
      createdAt: "2025-03-16",
      createdBy: "John Doe",
    },
    {
      id: "4-2",
      title: "Marketing Plan",
      url: "https://docs.example.com/marketing-plan",
      category: "Marketing",
      createdAt: "2025-03-20",
      createdBy: "Jane Smith",
    },
    {
      id: "4-3",
      title: "Press Release Draft",
      url: "https://docs.example.com/press-release",
      category: "PR",
      createdAt: "2025-03-25",
      createdBy: "Mike Wilson",
    },
    {
      id: "4-4",
      title: "Launch Event Details",
      url: "https://events.example.com/product-launch",
      category: "Event",
      createdAt: "2025-04-05",
      createdBy: "Jane Smith",
    },
    {
      id: "4-5",
      title: "Sales Training Materials",
      url: "https://training.example.com/new-product",
      category: "Sales",
      createdAt: "2025-04-10",
      createdBy: "John Doe",
    },
  ],
  "5": [
    {
      id: "5-1",
      title: "Infrastructure Assessment",
      url: "https://docs.example.com/infra-assessment",
      category: "Documentation",
      createdAt: "2025-05-02",
      createdBy: "Alex Johnson",
    },
    {
      id: "5-2",
      title: "Server Comparison",
      url: "https://docs.example.com/server-comparison",
      category: "Research",
      createdAt: "2025-05-08",
      createdBy: "Sarah Brown",
    },
    {
      id: "5-3",
      title: "Migration Plan",
      url: "https://docs.example.com/migration-plan",
      category: "Planning",
      createdAt: "2025-05-12",
      createdBy: "Alex Johnson",
    },
    {
      id: "5-4",
      title: "Budget Proposal",
      url: "https://docs.example.com/budget-proposal",
      category: "Finance",
      createdAt: "2025-05-15",
      createdBy: "Sarah Brown",
    },
    {
      id: "5-5",
      title: "Downtime Schedule",
      url: "https://calendar.example.com/server-downtime",
      category: "Planning",
      createdAt: "2025-05-20",
      createdBy: "Alex Johnson",
    },
  ],
}

// Project-specific files
export const projectFiles = {
  "1": [
    {
      id: "1-1",
      name: "Website_Requirements.pdf",
      type: "pdf",
      size: "2.4 MB",
      uploadedAt: "2025-03-05",
      uploadedBy: "John Doe",
    },
    {
      id: "1-2",
      name: "Design_Mockups.zip",
      type: "zip",
      size: "15.7 MB",
      uploadedAt: "2025-03-12",
      uploadedBy: "Jane Smith",
    },
    {
      id: "1-3",
      name: "Content_Inventory.xlsx",
      type: "xlsx",
      size: "1.8 MB",
      uploadedAt: "2025-03-18",
      uploadedBy: "Alex Johnson",
    },
    {
      id: "1-4",
      name: "SEO_Strategy.docx",
      type: "docx",
      size: "1.2 MB",
      uploadedAt: "2025-03-25",
      uploadedBy: "Jane Smith",
    },
    {
      id: "1-5",
      name: "Client_Feedback.pdf",
      type: "pdf",
      size: "3.5 MB",
      uploadedAt: "2025-04-05",
      uploadedBy: "John Doe",
    },
  ],
  "2": [
    {
      id: "2-1",
      name: "App_Requirements.pdf",
      type: "pdf",
      size: "3.2 MB",
      uploadedAt: "2025-04-12",
      uploadedBy: "John Doe",
    },
    {
      id: "2-2",
      name: "Wireframes.zip",
      type: "zip",
      size: "8.5 MB",
      uploadedAt: "2025-04-18",
      uploadedBy: "Sarah Brown",
    },
    {
      id: "2-3",
      name: "API_Documentation.pdf",
      type: "pdf",
      size: "4.7 MB",
      uploadedAt: "2025-04-20",
      uploadedBy: "Mike Wilson",
    },
    {
      id: "2-4",
      name: "User_Research.pptx",
      type: "pptx",
      size: "6.3 MB",
      uploadedAt: "2025-04-22",
      uploadedBy: "Sarah Brown",
    },
    {
      id: "2-5",
      name: "Development_Timeline.xlsx",
      type: "xlsx",
      size: "1.4 MB",
      uploadedAt: "2025-04-25",
      uploadedBy: "John Doe",
    },
  ],
  "3": [
    {
      id: "3-1",
      name: "Campaign_Brief.pdf",
      type: "pdf",
      size: "2.1 MB",
      uploadedAt: "2025-01-16",
      uploadedBy: "Jane Smith",
    },
    {
      id: "3-2",
      name: "Content_Calendar.xlsx",
      type: "xlsx",
      size: "1.8 MB",
      uploadedAt: "2025-01-22",
      uploadedBy: "Tom Davis",
    },
    {
      id: "3-3",
      name: "Social_Media_Assets.zip",
      type: "zip",
      size: "12.5 MB",
      uploadedAt: "2025-02-01",
      uploadedBy: "Jane Smith",
    },
    {
      id: "3-4",
      name: "Email_Templates.zip",
      type: "zip",
      size: "7.2 MB",
      uploadedAt: "2025-02-10",
      uploadedBy: "Tom Davis",
    },
    {
      id: "3-5",
      name: "Campaign_Results.pptx",
      type: "pptx",
      size: "8.4 MB",
      uploadedAt: "2025-03-28",
      uploadedBy: "Jane Smith",
    },
  ],
  "4": [
    {
      id: "4-1",
      name: "Product_Specifications.pdf",
      type: "pdf",
      size: "4.2 MB",
      uploadedAt: "2025-03-16",
      uploadedBy: "John Doe",
    },
    {
      id: "4-2",
      name: "Marketing_Plan.docx",
      type: "docx",
      size: "2.3 MB",
      uploadedAt: "2025-03-22",
      uploadedBy: "Jane Smith",
    },
    {
      id: "4-3",
      name: "Press_Release.docx",
      type: "docx",
      size: "1.1 MB",
      uploadedAt: "2025-03-28",
      uploadedBy: "Mike Wilson",
    },
    {
      id: "4-4",
      name: "Event_Planning.xlsx",
      type: "xlsx",
      size: "2.8 MB",
      uploadedAt: "2025-04-05",
      uploadedBy: "Jane Smith",
    },
    {
      id: "4-5",
      name: "Sales_Training.pptx",
      type: "pptx",
      size: "9.6 MB",
      uploadedAt: "2025-04-12",
      uploadedBy: "John Doe",
    },
  ],
  "5": [
    {
      id: "5-1",
      name: "Infrastructure_Assessment.pdf",
      type: "pdf",
      size: "3.8 MB",
      uploadedAt: "2025-05-02",
      uploadedBy: "Alex Johnson",
    },
    {
      id: "5-2",
      name: "Server_Comparison.xlsx",
      type: "xlsx",
      size: "2.1 MB",
      uploadedAt: "2025-05-08",
      uploadedBy: "Sarah Brown",
    },
    {
      id: "5-3",
      name: "Migration_Plan.docx",
      type: "docx",
      size: "1.9 MB",
      uploadedAt: "2025-05-15",
      uploadedBy: "Alex Johnson",
    },
    {
      id: "5-4",
      name: "Budget_Proposal.xlsx",
      type: "xlsx",
      size: "1.5 MB",
      uploadedAt: "2025-05-18",
      uploadedBy: "Sarah Brown",
    },
    {
      id: "5-5",
      name: "Downtime_Schedule.pdf",
      type: "pdf",
      size: "1.2 MB",
      uploadedAt: "2025-05-22",
      uploadedBy: "Alex Johnson",
    },
  ],
}

// Project-specific notes
export const projectNotes = {
  "1": [
    {
      id: "1-1",
      title: "Kickoff Meeting Notes",
      content:
        "Discussed project scope, timeline, and team responsibilities. Client emphasized mobile responsiveness and modern design.",
      createdAt: "2025-03-05",
      createdBy: "John Doe",
      category: "Meetings",
    },
    {
      id: "1-2",
      title: "Design Feedback",
      content:
        "Client liked the overall design direction but requested changes to the color scheme. Need to incorporate more brand colors.",
      createdAt: "2025-03-15",
      createdBy: "Jane Smith",
      category: "Design",
    },
    {
      id: "1-3",
      title: "Content Strategy",
      content:
        "Decided on a content-first approach. Will need to audit existing content and identify gaps before proceeding with design.",
      createdAt: "2025-03-20",
      createdBy: "Alex Johnson",
      category: "Content",
    },
    {
      id: "1-4",
      title: "Technical Requirements",
      content:
        "Website needs to support multiple languages, have a blog section, and integrate with the client's CRM system.",
      createdAt: "2025-03-25",
      createdBy: "John Doe",
      category: "Development",
    },
    {
      id: "1-5",
      title: "SEO Strategy",
      content:
        "Focus on improving page load speed, mobile usability, and implementing structured data for better search visibility.",
      createdAt: "2025-04-05",
      createdBy: "Jane Smith",
      category: "SEO",
    },
  ],
  "2": [
    {
      id: "2-1",
      title: "App Requirements Meeting",
      content:
        "Defined core features for MVP: user authentication, profile management, content browsing, and basic social features.",
      createdAt: "2025-04-12",
      createdBy: "John Doe",
      category: "Meetings",
    },
    {
      id: "2-2",
      title: "User Research Findings",
      content:
        "Target users prefer simple navigation and quick access to content. Privacy concerns are a major consideration.",
      createdAt: "2025-04-18",
      createdBy: "Sarah Brown",
      category: "Research",
    },
    {
      id: "2-3",
      title: "API Architecture",
      content:
        "Will use RESTful API design with JWT authentication. Need to implement rate limiting and proper error handling.",
      createdAt: "2025-04-22",
      createdBy: "Mike Wilson",
      category: "Development",
    },
    {
      id: "2-4",
      title: "UI/UX Guidelines",
      content:
        "App will follow Material Design principles with custom brand elements. Dark mode will be supported from launch.",
      createdAt: "2025-04-25",
      createdBy: "Sarah Brown",
      category: "Design",
    },
    {
      id: "2-5",
      title: "Testing Strategy",
      content:
        "Will implement unit tests for all core functionality and conduct beta testing with a small group of users before launch.",
      createdAt: "2025-04-28",
      createdBy: "Mike Wilson",
      category: "Testing",
    },
  ],
  "3": [
    {
      id: "3-1",
      title: "Campaign Goals",
      content:
        "Increase brand awareness by 20%, generate 500 qualified leads, and improve social media engagement by 30%.",
      createdAt: "2025-01-16",
      createdBy: "Jane Smith",
      category: "Planning",
    },
    {
      id: "3-2",
      title: "Content Themes",
      content:
        "Focus on industry trends, customer success stories, and educational content about our products and services.",
      createdAt: "2025-01-22",
      createdBy: "Tom Davis",
      category: "Content",
    },
    {
      id: "3-3",
      title: "Social Media Strategy",
      content:
        "Post frequency: LinkedIn (3x/week), Twitter (daily), Instagram (2x/week). Use hashtags consistently and engage with comments.",
      createdAt: "2025-01-28",
      createdBy: "Jane Smith",
      category: "Social Media",
    },
    {
      id: "3-4",
      title: "Email Campaign Plan",
      content:
        "Send 5 emails over 6 weeks: introduction, educational content, case study, special offer, and final reminder.",
      createdAt: "2025-02-05",
      createdBy: "Tom Davis",
      category: "Email",
    },
    {
      id: "3-5",
      title: "Campaign Results",
      content:
        "Exceeded goals: 25% increase in brand awareness, 650 leads generated, and 40% improvement in social engagement.",
      createdAt: "2025-03-28",
      createdBy: "Jane Smith",
      category: "Results",
    },
  ],
  "4": [
    {
      id: "4-1",
      title: "Product Features",
      content:
        "Key features include: advanced analytics, customizable dashboards, team collaboration tools, and API integrations.",
      createdAt: "2025-03-16",
      createdBy: "John Doe",
      category: "Product",
    },
    {
      id: "4-2",
      title: "Marketing Messaging",
      content: "Focus on how the product saves time, improves decision-making, and integrates with existing workflows.",
      createdAt: "2025-03-22",
      createdBy: "Jane Smith",
      category: "Marketing",
    },
    {
      id: "4-3",
      title: "Press Release Points",
      content: "Highlight innovative features, customer testimonials, and how the product addresses market gaps.",
      createdAt: "2025-03-28",
      createdBy: "Mike Wilson",
      category: "PR",
    },
    {
      id: "4-4",
      title: "Launch Event Planning",
      content:
        "Virtual event with product demo, customer panel, and Q&A session. Need to prepare presentation slides and demo script.",
      createdAt: "2025-04-05",
      createdBy: "Jane Smith",
      category: "Event",
    },
    {
      id: "4-5",
      title: "Sales Training Notes",
      content:
        "Sales team needs training on technical features, competitive advantages, and handling common objections.",
      createdAt: "2025-04-12",
      createdBy: "John Doe",
      category: "Sales",
    },
  ],
  "5": [
    {
      id: "5-1",
      title: "Current Infrastructure Issues",
      content:
        "Server capacity reaching limits, outdated hardware causing performance issues, and increasing maintenance costs.",
      createdAt: "2025-05-02",
      createdBy: "Alex Johnson",
      category: "Assessment",
    },
    {
      id: "5-2",
      title: "Server Options Comparison",
      content:
        "Compared cloud solutions (AWS, Azure, GCP) and on-premises options. Cloud solutions offer better scalability and lower upfront costs.",
      createdAt: "2025-05-08",
      createdBy: "Sarah Brown",
      category: "Research",
    },
    {
      id: "5-3",
      title: "Migration Strategy",
      content:
        "Phased approach: migrate non-critical systems first, then core applications. Need to plan for data transfer and testing.",
      createdAt: "2025-05-15",
      createdBy: "Alex Johnson",
      category: "Planning",
    },
    {
      id: "5-4",
      title: "Budget Considerations",
      content:
        "Initial investment higher for on-premises, but cloud costs add up over time. Need to consider 3-year TCO for accurate comparison.",
      createdAt: "2025-05-18",
      createdBy: "Sarah Brown",
      category: "Finance",
    },
    {
      id: "5-5",
      title: "Downtime Communication",
      content:
        "Need to notify all departments 2 weeks before migration. Planned downtime during weekend to minimize business impact.",
      createdAt: "2025-05-22",
      createdBy: "Alex Johnson",
      category: "Communication",
    },
  ],
}

export const projectStats = {
  totalProjects: 12,
  activeProjects: 5,
  completedProjects: 7,
  todoStats: {
    total: 45,
    completed: 28,
    inProgress: 12,
    pending: 5,
  },
  linkStats: {
    total: 32,
    byCategory: {
      Documentation: 12,
      Design: 8,
      Development: 7,
      Planning: 3,
      Team: 2,
    },
  },
  fileStats: {
    total: 67,
    totalSize: "256 MB",
    byType: {
      pdf: 15,
      docx: 12,
      xlsx: 8,
      pptx: 10,
      zip: 5,
      other: 17,
    },
  },
  noteStats: {
    total: 53,
    byCategory: {
      Meetings: 18,
      Requirements: 9,
      Design: 12,
      Development: 8,
      Testing: 6,
    },
  },
}

// For backward compatibility
export const todos = projectTodos["1"]
export const links = projectLinks["1"]
export const files = projectFiles["1"]
export const notes = projectNotes["1"]
